changes in Jenkinsfile: fixing build image stage

diff --git a/Jenkins/App_Pipeline/Jenkinsfile b/Jenkins/App_Pipeline/Jenkinsfile
--- a/Jenkins/App_Pipeline/Jenkinsfile
+++ b/Jenkins/App_Pipeline/Jenkinsfile
@@ -74,31 +74,29 @@ pipeline {
         //         '''
         //     }
         // }
-        stage('App Feature Testing: UnitTesting ') {
+        stage('App Feature Testing: UnitTesting') {
             steps {
-                script {
-                    sh '''
-                    echo "Starting unit tests..."
-                    cd App
-                    python3 -m venv venv
+                dir('App') {
+                    script {
+                        sh '''
+                        echo "Starting unit tests..."
+                        python3 -m venv venv
 
-                    # Activate virtual environment using bash
-                    bash -c "source venv/bin/activate && pip install -r requirements.txt && python3 manage.py test"
-                    result=$?
+                        # Activate virtual environment using bash
+                        bash -c "source venv/bin/activate && pip install -r requirements.txt && python3 manage.py test && deactivate"
+                        result=$?
 
-                    if [ $result -eq 0 ]; then
-                        echo "Unit tests passed successfully."
-                    else
-                        echo "Unit tests failed. Please check the test results."
-                        exit 1
-                    fi
-                    cd ..
-                '''
-
+                        if [ $result -eq 0 ]; then
+                            echo "Unit tests passed successfully."
+                        else
+                            echo "Unit tests failed. Please check the test results."
+                            exit 1
+                        fi
+                        '''
+                    }
                 }
             }
         }
-
         stage('Docker Image Build ') {
             steps {
                 script {
